In [1]:
!pip install numpy

In [3]:
import numpy as np

In [24]:
#creating array
a = np.array([122,77,88,90])
print(a)

[122  77  88  90]


In [13]:
b = np.array([[12,22,7, 8],[78,99,7,88]])
print(b)

[[12 22  7  8]
 [78 99  7 88]]


In [33]:
n = np.array([[[12,22.8,34],[5,9.8,8],[89,900,9]]])
print(n)

[[[ 12.   22.8  34. ]
  [  5.    9.8   8. ]
  [ 89.  900.    9. ]]]


In [35]:
#array properties findout
print(b.shape)
print(n.ndim)
print(a.size)
print (n.dtype)

(2, 4)
3
4
float64


In [57]:
#reshape the aarray 1d to 2d
arr= np.arange(0,9) #creates an array 7,8,9,...,9
# reshape it converts 1d arrya to a matrix
n = arr.reshape(3,3) #CRETAES 3 ROWS AND 4  COLUMNS
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
# flattened it converts matrix to 1d array
f = b.flatten()
print(f)

[12 22  7  8 78 99  7 88]


In [83]:
# slicing and indexing 
bb = np.array([[23,7,8],[99,9,9],[33,9,9]])
print(bb)
print(bb[0,:]) # prints the row # 1st row 

print(bb[:,1]) # prints the column


[[23  7  8]
 [99  9  9]
 [33  9  9]]
[23  7  8]
[7 9 9]


In [85]:
 arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print(arr + scalar)  # Adds 10 to each element
 

[[11 12 13]
 [14 15 16]]


In [9]:
import numpy as np
x = np.random.rand() # picks a random float number

o = np.random.rand(8)
print(o)
print(x)

[0.17158807 0.3872073  0.94131192 0.96025321 0.44712547 0.73419953
 0.74508475 0.65444188]
0.8705488478373699


In [11]:
i = np.random.randint(1,8)
print(i)

2


In [66]:
#making a array from random integers 

u = np.random.randint(1,19, size=(3,4))
print(np.random.randint(1,8, (3,3)))
print(u)

[[3 5 2]
 [3 1 6]
 [6 1 3]]
[[ 4  8  4  4]
 [ 7 14  5  2]
 [15  8  5  1]]


In [60]:
ii = np.array([[1,2,5,8],[7,8,9,0]])
np.random.shuffle(ii)
print(ii)
#shuffling a array randomly


[[7 8 9 0]
 [1 2 5 8]]


In [26]:
#random choice from the array only workes for one dimensional array
c = np.random.choice(a)
print(c)


90


In [49]:
np.random.seed(44) # to get a fixed number with a seed but the number will change 
#as you change the seed number
print(np.random.rand(5))

[0.83484215 0.1047961  0.74464048 0.36050084 0.35931084]


In [ ]:
d(22)
x= np.random.

In [44]:
np.random.seed(22)
x= np.random.randint(9,12,size=6)
print(x)

[10  9  9  9  9 11]


In [3]:
# cretae  a data set in radom numbers in numpy
import numpy as np
dataset = np.random.randint(0,100,size=(10,),dtype= np.int32)
print(dataset)

[52 41 38 17 41 48 76 88 76 27]


In [15]:
# create a simple linear regression dataset ( x and y)

x = np.array ([12,23, 26,89, 90,89])
y=np.array ([12,50,66,5,89])

print('Features (x):',y) 

Features (x): [12 50 66  5 89]


In [21]:
# handeling missing values 

dataset = np.array([[12,2,np.nan ,],[np.nan, 78,9,]])

mean = np.nanmean(dataset) # here nanmean means mean without the missing values
print (mean)

# fills missing values with mean
dataset[np.isnan(dataset)]= mean
print(dataset)


25.25
[[12.    2.   25.25]
 [25.25 78.    9.  ]]


In [23]:
#machine learning concepts with numpy
# how to build each concept from scratch
# models i am going to cover
# simple linear regression
# KNN
#logistic regression
# descision tree
# principal Compotent analysis
#descision trees
# naive byes classifier


In [25]:
#simple linear regression in numpy

#frist create a data set

# Generate random data for X (100 samples)
np.random.seed(42)
X = np.random.rand(100, 1) * 10  # Features
y = 2.5 * X + np.random.randn(100, 1)  # True relationship with noise

# Initialize weights and bias
m = 0  # slope
c = 0  # intercept
learning_rate = 0.01
epochs = 1000
n = len(X)  # number of samples

# Gradient Descent
for _ in range(epochs):
    y_pred = m * X + c
    error = y_pred - y

    # Partial derivatives (Gradients)
    dm = (2/n) * np.sum(X * error)
    dc = (2/n) * np.sum(error)

    # Update parameters
    m -= learning_rate * dm
    c -= learning_rate * dc

print(f"Trained Model: y = {m:.2f}x + {c:.2f}")



Trained Model: y = 2.45x + 0.22


In [27]:
# mean squred error (mse( for regression to predict the qaccuracy
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Example
y_true = np.array([3, 5, 7])
y_pred = np.array([2.5, 5.5, 7.1])

print(f"MSE: {mse(y_true, y_pred):.4f}")


MSE: 0.1700


In [29]:
# logistic regression for binary classification

# Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Loss Function: Binary Cross-Entropy
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Logistic Regression Model
class LogisticRegression:
    def __init__(self, learning_rate=0.01, epochs=1000):
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X, y):
        self.m, self.n = X.shape
        self.weights = np.zeros(self.n)
        self.bias = 0

        for _ in range(self.epochs):
            linear_model = np.dot(X, self.weights) + self.bias
            y_pred = sigmoid(linear_model)

            # Gradients
            dw = (1 / self.m) * np.dot(X.T, (y_pred - y))
            db = (1 / self.m) * np.sum(y_pred - y)

            # Update weights
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_pred = sigmoid(linear_model)
        return np.where(y_pred >= 0.5, 1, 0)

# Example Dataset
X = np.array([[0.5, 1.2], [1.0, 2.5], [1.5, 3.0], [3.0, 3.5]])
y = np.array([0, 0, 1, 1])

# Train the Model
model = LogisticRegression(learning_rate=0.1, epochs=1000)
model.fit(X, y)

# Predict
predictions = model.predict(X)
print("Predictions:", predictions)


Predictions: [0 0 1 1]


In [31]:
# support vector machine SVM
class SVM:
    def __init__(self, learning_rate=0.001, lambda_param=0.01, epochs=1000):
        self.lr = learning_rate
        self.lambda_param = lambda_param
        self.epochs = epochs

    def fit(self, X, y):
        y = np.where(y <= 0, -1, 1)  # Convert labels to -1 or 1
        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for _ in range(self.epochs):
            for idx, x_i in enumerate(X):
                condition = y[idx] * (np.dot(x_i, self.weights) - self.bias) >= 1
                if condition:
                    self.weights -= self.lr * (2 * self.lambda_param * self.weights)
                else:
                    self.weights -= self.lr * (2 * self.lambda_param * self.weights - np.dot(x_i, y[idx]))
                    self.bias -= self.lr * y[idx]

    def predict(self, X):
        linear_output = np.dot(X, self.weights) - self.bias
        return np.sign(linear_output)

# Example Dataset
X = np.array([[2, 3], [1, 1], [4, 5], [6, 5]])
y = np.array([1, -1, 1, -1])

# Train SVM Model
svm = SVM()
svm.fit(X, y)

# Predict
predictions = svm.predict(X)
print("SVM Predictions:", predictions)



SVM Predictions: [ 1. -1.  1. -1.]


In [33]:
# descision tree gini and entropy 
class DecisionTree:
    def __init__(self, depth=3):
        self.depth = depth

    def fit(self, X, y):
        self.tree = self._grow_tree(X, y)

    def _gini(self, y):
        classes, counts = np.unique(y, return_counts=True)
        probabilities = counts / len(y)
        return 1 - np.sum(probabilities**2)

    def _best_split(self, X, y):
        best_gini = float('inf')
        best_feature, best_threshold = None, None

        for feature in range(X.shape[1]):
            thresholds = np.unique(X[:, feature])
            for threshold in thresholds:
                left_indices = X[:, feature] <= threshold
                right_indices = ~left_indices
                if sum(left_indices) == 0 or sum(right_indices) == 0:
                    continue

                gini = (
                    (sum(left_indices) / len(y)) * self._gini(y[left_indices]) +
                    (sum(right_indices) / len(y)) * self._gini(y[right_indices])
                )

                if gini < best_gini:
                    best_gini = gini
                    best_feature = feature
                    best_threshold = threshold

        return best_feature, best_threshold

    def _grow_tree(self, X, y, depth=0):
        if depth == self.depth or len(np.unique(y)) == 1:
            return np.argmax(np.bincount(y))

        feature, threshold = self._best_split(X, y)
        left_indices = X[:, feature] <= threshold
        right_indices = ~left_indices

        return {
            'feature': feature,
            'threshold': threshold,
            'left': self._grow_tree(X[left_indices], y[left_indices], depth+1),
            'right': self._grow_tree(X[right_indices], y[right_indices], depth+1)
        }

    def predict(self, X):
        return np.array([self._predict(sample, self.tree) for sample in X])

    def _predict(self, sample, tree):
        if isinstance(tree, np.int64):
            return tree
        feature = tree['feature']
        if sample[feature] <= tree['threshold']:
            return self._predict(sample, tree['left'])
        else:
            return self._predict(sample, tree['right'])

# Example Dataset
X = np.array([[2, 3], [1, 1], [4, 5], [6, 5]])
y = np.array([0, 0, 1, 1])

# Train Decision Tree
tree = DecisionTree(depth=2)
tree.fit(X, y)

# Predict
predictions = tree.predict(X)
print("Decision Tree Predictions:", predictions)


Decision Tree Predictions: [0 0 1 1]


In [35]:
# PCA principle compotent analysis 
def pca(X, n_components=2):
    # Standardize
    X_meaned = X - np.mean(X, axis=0)

    # Covariance matrix
    cov_matrix = np.cov(X_meaned, rowvar=False)

    # Eigen decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

    # Sort eigenvectors by largest eigenvalues
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvectors = eigenvectors[:, sorted_indices]

    # Select top components
    components = eigenvectors[:, :n_components]

    # Project data
    return np.dot(X_meaned, components)

# Example Dataset
X = np.array([[2, 8], [3, 7], [5, 6], [6, 5]])

# Perform PCA
X_pca = pca(X, n_components=1)
print("PCA Reduced Data:\n", X_pca)


PCA Reduced Data:
 [[ 2.49890378]
 [ 1.10543978]
 [-1.10543978]
 [-2.49890378]]
